# Generated by Django 4.2.7 on 2026-09-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_type', models.CharField(choices=[('pdf', 'Генератор PDF'), ('email', 'Парсер email')], max_length=20, verbose_name='Тип бота')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Выполняется'), ('success', 'Успешно'), ('failure', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('input_data', models.JSONField(blank=True, default=dict, verbose_name='Входные данные')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/', verbose_name='Файл результата')),
                ('result_log', models.TextField(blank=True, default='', verbose_name='Лог выполнения')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало выполнения')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='tasks_task_status_8e5503_idx'), models.Index(fields=['bot_type'], name='tasks_task_bot_typ_7102f5_idx')],
            },
        ),
    ]
